# Generated by Django 5.0.7 on 2024-10-07 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocente',
            fields=[
                ('categoriaCodigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('facultadCodigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('UniversidadCodigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('escuelaCodigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
                ('facultadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facultad')),
                ('UniversidadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocente',
            fields=[
                ('tipoDocenteCodigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
                ('UniversidadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('periodoAcademicoCodigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('anio', models.SmallIntegerField()),
                ('fechaIni', models.DateField()),
                ('fechaFinal', models.DateField()),
                ('estado', models.CharField(choices=[('A', 'Abierto'), ('C', 'Cerrado')], max_length=15)),
                ('UniversidadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
        ),
        migrations.AddField(
            model_name='facultad',
            name='UniversidadCodigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad'),
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Docentecodigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('U', 'Unión Libre'), ('V', 'Viudo')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Jubilado', 'Jubilado'), ('Sabático', 'Sabático'), ('Licencia', 'Licencia')], max_length=10)),
                ('categoriaCodigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.categoriadocente')),
                ('escuelaCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.escuela')),
                ('facultadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facultad')),
                ('tipoDocenteCodigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocente')),
                ('UniversidadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
        ),
        migrations.AddField(
            model_name='categoriadocente',
            name='UniversidadCodigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad'),
        ),
    ]
