# Generated by Django 4.2.19 on 2025-05-04 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('CampusID', models.AutoField(primary_key=True, serialize=False)),
                ('CampusCodigo', models.CharField(max_length=25, unique=True)),
                ('CampusNombre', models.CharField(max_length=100, unique=True)),
                ('CampusDireccion', models.CharField(blank=True, max_length=255, null=True)),
                ('CampusPais', models.CharField(blank=True, max_length=100, null=True)),
                ('CampusProvincia', models.CharField(blank=True, max_length=100, null=True)),
                ('CampusCiudad', models.CharField(blank=True, max_length=100, null=True)),
                ('CampusTelefono', models.CharField(blank=True, max_length=50, null=True)),
                ('CampusCorreoContacto', models.CharField(blank=True, max_length=100, null=True)),
                ('CampusFechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(blank=True, default='admin', max_length=50, null=True)),
                ('CampusEstado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaDocente',
            fields=[
                ('CategoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('categoriaCodigo', models.CharField(max_length=25, unique=True)),
                ('CategoriaNombre', models.CharField(max_length=100, unique=True)),
                ('CategoriaEstado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
                ('CategoriaFechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(blank=True, default='admin', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('UniversidadID', models.AutoField(primary_key=True, serialize=False)),
                ('UniversidadCodigo', models.CharField(max_length=25, unique=True)),
                ('UniversidadNombre', models.CharField(max_length=55, unique=True)),
                ('UniversidadDireccion', models.CharField(max_length=200)),
                ('UniversidadTelefono', models.CharField(max_length=20)),
                ('UniversidadEmail', models.CharField(max_length=55)),
                ('UniversidadSitioWeb', models.CharField(max_length=55)),
                ('UniversidadRector', models.CharField(max_length=55)),
                ('UniversidadFechaRegistro', models.DateField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(default='admin', max_length=55)),
                ('UniversidadEstado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
            ],
            options={
                'indexes': [models.Index(fields=['UniversidadCodigo'], name='idx_universidad_codigo'), models.Index(fields=['UniversidadNombre'], name='idx_universidad_nombre')],
            },
        ),
        migrations.CreateModel(
            name='TipoDocente',
            fields=[
                ('TipoDocenteID', models.AutoField(primary_key=True, serialize=False)),
                ('TipoDocenteCodigo', models.CharField(max_length=25, unique=True)),
                ('TipoDocenteDescripcion', models.CharField(max_length=255, unique=True)),
                ('TipoDocenteEstado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
                ('TipoFechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(blank=True, default='admin', max_length=50, null=True)),
                ('TipoDocente_UniversidadFK', models.ForeignKey(db_column='UniversidadCodigo', on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
            options={
                'db_table': 'TipoDocente',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('PeriodoID', models.AutoField(primary_key=True, serialize=False)),
                ('PeriodoCodigo', models.CharField(max_length=25, unique=True)),
                ('PeriodoNombre', models.CharField(max_length=100, unique=True)),
                ('PeriodoTipo', models.CharField(max_length=20)),
                ('PeriodoAnio', models.IntegerField()),
                ('PeriodoFechaInicio', models.DateField()),
                ('PeriodoFechaFin', models.DateField()),
                ('PeriodoFechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(blank=True, default='admin', max_length=50, null=True)),
                ('PeriodoEstado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
                ('Periodo_UniversidadFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
            options={
                'db_table': 'PeriodoAcademico',
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('FacultadID', models.AutoField(primary_key=True, serialize=False)),
                ('FacultadCodigo', models.CharField(max_length=25, unique=True)),
                ('FacultadNombre', models.CharField(max_length=100, unique=True)),
                ('FacultadDecano', models.CharField(max_length=100)),
                ('FacultadDireccion', models.CharField(max_length=100)),
                ('FacultadTelefono', models.CharField(max_length=100)),
                ('FacultadEmail', models.CharField(max_length=100)),
                ('FacultadFechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(blank=True, default='admin', max_length=50, null=True)),
                ('FacultadEstado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
                ('Facultad_CampusFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.campus')),
                ('Facultad_UniversidadFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('EscuelaId', models.AutoField(primary_key=True, serialize=False)),
                ('EscuelaCodigo', models.CharField(max_length=25, unique=True)),
                ('EscuelaNombre', models.CharField(max_length=100, unique=True)),
                ('EscuelaDirectora', models.CharField(max_length=100)),
                ('EscuelaTelefono', models.CharField(max_length=100)),
                ('EscuelaCorreo', models.CharField(max_length=100)),
                ('EscuelaFechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(blank=True, default='admin', max_length=50, null=True)),
                ('EscuelaEstado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
                ('Escuela_UniversidadFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
                ('Escuela_facultadFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('DocenteID', models.AutoField(primary_key=True, serialize=False)),
                ('DocenteCodigo', models.CharField(max_length=10, unique=True)),
                ('DocenteNombre', models.CharField(max_length=100)),
                ('DocenteApellido', models.CharField(max_length=100)),
                ('DocenteSexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('DocenteEstadoCivil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Union Libre', 'Unión Libre'), ('Viudo', 'Viudo')], max_length=20)),
                ('DocenteFechaNacimiento', models.DateField(blank=True, null=True)),
                ('DocenteLugarNacimiento', models.CharField(max_length=100)),
                ('DocenteFechaIngreso', models.DateField(blank=True, null=True)),
                ('DocenteNacionalidad', models.CharField(max_length=50)),
                ('DocenteTipoIdentificacion', models.CharField(max_length=20)),
                ('DocenteNumeroIdentificacion', models.CharField(max_length=20)),
                ('DocenteTelefono', models.CharField(max_length=20)),
                ('DocenteCorreoElectronico', models.EmailField(max_length=100)),
                ('DocenteDireccion', models.CharField(max_length=200)),
                ('DocenteEstado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
                ('DocenteObservaciones', models.TextField(blank=True, null=True)),
                ('DocenteFechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(default='admin', max_length=50)),
                ('Docente_CategoriaDocenteFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.categoriadocente')),
                ('Docente_TipoDocenteFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocente')),
                ('Docente_UniversidadFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
            options={
                'db_table': 'Docente',
            },
        ),
        migrations.AddField(
            model_name='categoriadocente',
            name='Categoria_UniversidadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad'),
        ),
        migrations.AddField(
            model_name='campus',
            name='Campus_UniversidadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad'),
        ),
        migrations.CreateModel(
            name='AsignacionDocente',
            fields=[
                ('AsignacionID', models.AutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=10, unique=True)),
                ('clave', models.CharField(max_length=10)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('seccion', models.CharField(blank=True, max_length=10, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=30, null=True)),
                ('cupo', models.IntegerField(blank=True, null=True)),
                ('inscripto', models.IntegerField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=100, null=True)),
                ('dias', models.CharField(blank=True, max_length=50, null=True)),
                ('aula', models.CharField(blank=True, max_length=50, null=True)),
                ('creditos', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('accion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('campusFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.campus')),
                ('docenteFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.docente')),
                ('escuelaFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.escuela')),
                ('facultadFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facultad')),
                ('periodoFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.periodoacademico')),
                ('universidadFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
            options={
                'db_table': 'AsignacionDocente',
            },
        ),
        migrations.AddIndex(
            model_name='tipodocente',
            index=models.Index(fields=['TipoDocenteDescripcion'], name='idx_tipo_descripcion'),
        ),
        migrations.AddIndex(
            model_name='tipodocente',
            index=models.Index(fields=['TipoDocenteEstado'], name='idx_tipo_estado'),
        ),
        migrations.AddIndex(
            model_name='periodoacademico',
            index=models.Index(fields=['PeriodoEstado'], name='idx_periodo_estado'),
        ),
        migrations.AddIndex(
            model_name='periodoacademico',
            index=models.Index(fields=['PeriodoAnio'], name='idx_periodo_anio'),
        ),
        migrations.AddIndex(
            model_name='facultad',
            index=models.Index(fields=['FacultadCodigo'], name='idx_facultad_codigo'),
        ),
        migrations.AddIndex(
            model_name='facultad',
            index=models.Index(fields=['FacultadNombre'], name='idx_facultad_nombre'),
        ),
        migrations.AddIndex(
            model_name='facultad',
            index=models.Index(fields=['FacultadEstado'], name='idx_facultad_estado'),
        ),
        migrations.AddIndex(
            model_name='escuela',
            index=models.Index(fields=['EscuelaNombre'], name='idx_escuela_nombre'),
        ),
        migrations.AddIndex(
            model_name='escuela',
            index=models.Index(fields=['EscuelaEstado'], name='idx_escuela_estado'),
        ),
        migrations.AddIndex(
            model_name='docente',
            index=models.Index(fields=['DocenteCodigo'], name='Docente_Docente_88c7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='docente',
            index=models.Index(fields=['Docente_UniversidadFK'], name='Docente_Docente_19fe7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together={('DocenteNumeroIdentificacion', 'Docente_UniversidadFK')},
        ),
        migrations.AddIndex(
            model_name='categoriadocente',
            index=models.Index(fields=['CategoriaNombre'], name='idx_categiria_nombre'),
        ),
        migrations.AddIndex(
            model_name='categoriadocente',
            index=models.Index(fields=['CategoriaEstado'], name='idx_categoria_estado'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['CampusEstado'], name='idx_campus_estado'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['CampusNombre'], name='idx_campus_nombre'),
        ),
    ]
