# Generated by Django 4.2.19 on 2025-02-17 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocente',
            fields=[
                ('categoriaCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('UniversidadCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=110)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
            ],
            options={
                'unique_together': {('nombre', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='TipoDocente',
            fields=[
                ('tipoDocenteCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
                ('UniversidadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
            options={
                'unique_together': {('nombre', 'estado', 'UniversidadCodigo')},
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('facultadCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
                ('UniversidadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
            options={
                'unique_together': {('nombre', 'estado', 'UniversidadCodigo')},
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('escuelaCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=15)),
                ('UniversidadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
                ('facultadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facultad')),
            ],
            options={
                'unique_together': {('nombre', 'estado', 'UniversidadCodigo', 'facultadCodigo')},
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Docentecodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55)),
                ('apellidos', models.CharField(max_length=55)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2)),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Union Libre', 'Unión Libre'), ('Viudo', 'Viudo')], max_length=15)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Jubilado', 'Jubilado'), ('Sabático', 'Sabático'), ('Licencia', 'Licencia')], max_length=15)),
                ('UniversidadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
                ('categoriaCodigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.categoriadocente')),
                ('escuelaCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.escuela')),
                ('facultadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facultad')),
                ('tipoDocenteCodigo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.tipodocente')),
            ],
            options={
                'unique_together': {('nombre', 'estado', 'apellidos', 'sexo', 'estado_civil', 'fecha_nacimiento', 'telefono', 'direccion', 'UniversidadCodigo')},
            },
        ),
        migrations.AddField(
            model_name='categoriadocente',
            name='UniversidadCodigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad'),
        ),
        migrations.CreateModel(
            name='asignacionDocente',
            fields=[
                ('ADIDcodigo', models.AutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=40)),
                ('clave', models.CharField(max_length=40)),
                ('asignatura', models.CharField(max_length=40)),
                ('codigo', models.CharField(max_length=40)),
                ('seccion', models.CharField(max_length=40)),
                ('modalidad', models.CharField(max_length=40)),
                ('campus', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('cupo', models.CharField(max_length=40)),
                ('inscripto', models.CharField(max_length=40)),
                ('horario', models.CharField(max_length=40)),
                ('dias', models.CharField(max_length=40)),
                ('Aula', models.CharField(max_length=40)),
                ('creditos', models.CharField(max_length=40)),
                ('period', models.CharField(default='2025-20', max_length=7)),
                ('DocenteCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.docente')),
                ('escuelaCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.escuela')),
                ('facultadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('periodoAcademicoCodigo', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], max_length=15)),
                ('UniversidadCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.universidad')),
            ],
            options={
                'unique_together': {('nombre', 'estado', 'UniversidadCodigo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='categoriadocente',
            unique_together={('nombre', 'estado', 'UniversidadCodigo')},
        ),
    ]
