# Generated by Django 4.2.19 on 2025-02-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together={('nombre', 'apellidos', 'telefono', 'UniversidadCodigo')},
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='period',
            field=models.CharField(default='2025-20', max_length=40),
        ),
        migrations.AlterField(
            model_name='docente',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='escuela',
            unique_together={('nombre', 'UniversidadCodigo', 'facultadCodigo')},
        ),
        migrations.AlterUniqueTogether(
            name='facultad',
            unique_together={('nombre', 'UniversidadCodigo')},
        ),
        migrations.AddIndex(
            model_name='docente',
            index=models.Index(fields=['nombre', 'apellidos', 'telefono', 'UniversidadCodigo'], name='myapp_docen_nombre_ca6733_idx'),
        ),
    ]
