# Generated by Django 4.2.19 on 2025-05-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_docente_docente_88c7c3_idx_myapp_docen_docente_9f73d6_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignaciondocente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tipodocente',
            table=None,
        ),
    ]
