# Generated by Django 4.2.19 on 2025-05-04 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_asignaciondocente_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='periodoacademico',
            table=None,
        ),
    ]
