# Generated by Django 4.2.19 on 2025-05-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_periodoacademico_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciondocente',
            name='accion',
            field=models.CharField(blank=True, default='nuevo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='nrc',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='usuario_registro',
            field=models.CharField(blank=True, default='admin', max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='asignaciondocente',
            constraint=models.UniqueConstraint(fields=('nrc', 'periodoFk'), name='unique_nrc_periodo'),
        ),
    ]
