# Generated by Django 5.0.7 on 2024-12-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_universidad_universidadcodigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadocente',
            name='categoriaCodigo',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='docente',
            name='Docentecodigo',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='escuelaCodigo',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='facultadCodigo',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='periodoAcademicoCodigo',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipodocente',
            name='tipoDocenteCodigo',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
