# Generated by Django 4.2.19 on 2025-06-05 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_alter_asignaciondocente_accion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='PeriodoEstado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
        migrations.AddIndex(
            model_name='asignaciondocente',
            index=models.Index(fields=['nrc'], name='idx_asignacion_nrc'),
        ),
        migrations.AddIndex(
            model_name='asignaciondocente',
            index=models.Index(fields=['periodoFk'], name='idx_asignacion_periodo'),
        ),
        migrations.AddIndex(
            model_name='asignaciondocente',
            index=models.Index(fields=['docenteFk'], name='idx_asignacion_docente'),
        ),
        migrations.AddIndex(
            model_name='asignaciondocente',
            index=models.Index(fields=['campusFk'], name='idx_asignacion_campus'),
        ),
        migrations.AddIndex(
            model_name='asignaciondocente',
            index=models.Index(fields=['facultadFk'], name='idx_asignacion_facultad'),
        ),
        migrations.AddField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
