# Generated by Django 5.1.4 on 2024-12-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_categoriadocente_categoriacodigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
