# Generated by Django 4.2.19 on 2025-06-05 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_apilog_alter_periodoacademico_periodoestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='CampusEstado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='categoriadocente',
            name='CategoriaEstado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='EscuelaEstado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='FacultadEstado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='tipodocente',
            name='TipoDocenteEstado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='UniversidadEstado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
    ]
