# Generated by Django 5.1.4 on 2025-01-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_docente_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondocente',
            name='period',
            field=models.CharField(default='2025-20', max_length=7),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='Aula',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='asignatura',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='campus',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='clave',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='codigo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='creditos',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='cupo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='dias',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='horario',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='inscripto',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='modalidad',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='nrc',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='seccion',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='tipo',
            field=models.CharField(max_length=40),
        ),
    ]
