# Generated by Django 4.2.19 on 2025-07-22 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_campus_campusestado_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='categoriadocente',
            new_name='idx_categoria_nombre',
            old_name='idx_categiria_nombre',
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='campusFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.campus'),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='docenteFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.docente'),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='escuelaFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.escuela'),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='facultadFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.facultad'),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='periodoFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.periodoacademico'),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='universidadFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='myapp.universidad'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='Campus_UniversidadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_list', to='myapp.universidad'),
        ),
        migrations.AlterField(
            model_name='categoriadocente',
            name='Categoria_UniversidadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_docente', to='myapp.universidad'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='Docente_CategoriaDocenteFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='myapp.categoriadocente'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='Docente_TipoDocenteFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='myapp.tipodocente'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='Docente_UniversidadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='myapp.universidad'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='Escuela_UniversidadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='myapp.universidad'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='Escuela_facultadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='myapp.facultad'),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='Facultad_CampusFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultades', to='myapp.campus'),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='Facultad_UniversidadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultades', to='myapp.universidad'),
        ),
        migrations.AlterField(
            model_name='periodoacademico',
            name='Periodo_UniversidadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='myapp.universidad'),
        ),
        migrations.AlterField(
            model_name='tipodocente',
            name='TipoDocente_UniversidadFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_docente', to='myapp.universidad'),
        ),
    ]
