# Generated by Django 5.1.4 on 2025-01-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_asignaciondocente_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodoacademico',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='periodoacademico',
            name='fechaFinal',
        ),
        migrations.RemoveField(
            model_name='periodoacademico',
            name='fechaIni',
        ),
    ]
