# Generated by Django 4.2.19 on 2025-08-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_idx_categiria_nombre_idx_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondocente',
            name='comentario',
            field=models.CharField(blank=True, default='observaciones', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='accion',
            field=models.CharField(blank=True, default='Pendiente Asignar', max_length=50, null=True),
        ),
    ]
