# Generated by Django 5.1.4 on 2025-01-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_periodoacademico_anio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaciondocente',
            name='id',
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='ADIDcodigo',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
