# Generated by Django 4.2.19 on 2025-08-30 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_asignaciondocente_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('AsignaturaCodigo', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('AsignaturaNombre', models.CharField(max_length=100)),
                ('AsignaturaCreditos', models.IntegerField(default=0)),
                ('AsignaturaHorasTeoricas', models.IntegerField(default=0)),
                ('AsignaturaHorasPracticas', models.IntegerField(default=0)),
                ('AsignaturaEstado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15)),
                ('AsignaturaFechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(blank=True, default='admin', max_length=50, null=True)),
                ('Asignatura_EscuelaFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='myapp.escuela')),
                ('Asignatura_FacultadFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='myapp.facultad')),
                ('Asignatura_UniversidadFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='myapp.universidad')),
            ],
            options={
                'indexes': [models.Index(fields=['AsignaturaNombre'], name='idx_asignatura_nombre'), models.Index(fields=['AsignaturaEstado'], name='idx_asignatura_estado')],
            },
        ),
    ]
