# Generated by Django 5.1.4 on 2025-02-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_periodoacademico_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='universidad',
            unique_together={('nombre', 'estado')},
        ),
    ]
