# Generated by Django 5.1.4 on 2025-02-14 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_universidad_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categoriadocente',
            unique_together={('nombre', 'estado', 'UniversidadCodigo')},
        ),
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together={('nombre', 'estado', 'apellidos', 'sexo', 'estado_civil', 'fecha_nacimiento', 'telefono', 'direccion', 'UniversidadCodigo')},
        ),
        migrations.AlterUniqueTogether(
            name='escuela',
            unique_together={('nombre', 'estado', 'UniversidadCodigo', 'facultadCodigo')},
        ),
        migrations.AlterUniqueTogether(
            name='facultad',
            unique_together={('nombre', 'estado', 'UniversidadCodigo')},
        ),
        migrations.AlterUniqueTogether(
            name='periodoacademico',
            unique_together={('nombre', 'estado', 'UniversidadCodigo')},
        ),
        migrations.AlterUniqueTogether(
            name='tipodocente',
            unique_together={('nombre', 'estado', 'UniversidadCodigo')},
        ),
    ]
