# Generated by Django 4.2.19 on 2025-10-24 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaciondocente',
            name='accion',
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='modificacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_escuela', to='myapp.escuela'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facultad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_facultad', to='myapp.facultad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='universidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_universidad', to='myapp.universidad'),
        ),
    ]
