# Generated by Django 4.2.19 on 2025-10-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_asignaciondocente_accion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciondocente',
            name='modificacion',
            field=models.CharField(blank=True, default='Pendiente Modificar', max_length=100),
        ),
    ]
