# Generated by Django 5.1.4 on 2025-02-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_categoriadocente_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='apellidos',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='docente',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Jubilado', 'Jubilado'), ('Sabático', 'Sabático'), ('Licencia', 'Licencia')], max_length=15),
        ),
        migrations.AlterField(
            model_name='docente',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Union Libre', 'Unión Libre'), ('Viudo', 'Viudo')], max_length=15),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='docente',
            name='telefono',
            field=models.CharField(max_length=30),
        ),
    ]
