# Generated by Django 4.2.19 on 2025-10-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_asignaciondocente_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondocente',
            name='accion',
            field=models.CharField(blank=True, default='Pendiente Asignar', max_length=50, null=True),
        ),
    ]
