# Generated by Django 4.2.19 on 2025-02-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_docente_sexo_alter_universidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=2),
        ),
    ]
