# Generated by Django 4.2.19 on 2025-10-29 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_asignaciondocente_accion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='docente',
            unique_together=set(),
        ),
    ]
