# Generated by Django 4.2.19 on 2025-10-31 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_docente_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='CampusDirector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='nrc',
            field=models.CharField(blank=True, default='N/A', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='DocenteEstado',
            field=models.CharField(default='Activo', max_length=50),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('StatusCodigo', models.CharField(max_length=25, unique=True)),
                ('StatusNombre', models.CharField(max_length=50, unique=True)),
                ('StatusDescripcion', models.CharField(max_length=255)),
                ('StatusFechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(blank=True, default='admin', max_length=50, null=True)),
                ('Status_UniversidadFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_lista', to='myapp.universidad')),
            ],
            options={
                'indexes': [models.Index(fields=['StatusNombre'], name='idx_status_nombre')],
            },
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('AccionID', models.AutoField(primary_key=True, serialize=False)),
                ('AccionCodigo', models.CharField(max_length=25, unique=True)),
                ('AccionNombre', models.CharField(max_length=50, unique=True)),
                ('AccionDescripcion', models.CharField(max_length=255)),
                ('AccionFechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('UsuarioRegistro', models.CharField(blank=True, default='admin', max_length=50, null=True)),
                ('Accion_UniversidadFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_lista', to='myapp.universidad')),
            ],
            options={
                'indexes': [models.Index(fields=['AccionNombre'], name='idx_accion_nombre')],
            },
        ),
    ]
