# Generated by Django 4.2.19 on 2025-10-31 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_campus_campusdirector_alter_asignaciondocente_nrc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accion',
            name='AccionDescripcion',
        ),
        migrations.RemoveField(
            model_name='status',
            name='StatusDescripcion',
        ),
    ]
