# Generated by Django 4.2.19 on 2025-10-31 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_accion_acciondescripcion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asignaciondocente',
            name='unique_nrc_periodo',
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='docenteFk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='myapp.docente'),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='modificacion',
            field=models.CharField(blank=True, default='Pendiente Modificar', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asignaciondocente',
            name='nrc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='asignaciondocente',
            constraint=models.UniqueConstraint(condition=models.Q(('nrc__isnull', False)), fields=('nrc', 'periodoFk'), name='unique_nrc_periodo'),
        ),
    ]
