# Generated by Django 4.2.19 on 2025-10-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_asignaciondocente_unique_nrc_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciondocente',
            name='modificacion',
            field=models.CharField(blank=True, default='--------', max_length=100, null=True),
        ),
    ]
