# Generated by Django 4.2.19 on 2025-11-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_asignaciondocente_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='DocenteCelular',
            field=models.CharField(default='88888888', max_length=20),
        ),
    ]
