# Generated by Django 4.2.19 on 2026-01-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_docente_docentecelular'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asignaciondocente',
            name='unique_nrc_periodo',
        ),
        migrations.AddField(
            model_name='accion',
            name='AccionStatus',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
    ]
