# Generated by Django 4.2.19 on 2026-01-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_asignaciondocente_unique_nrc_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='StatusEstado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=15),
        ),
    ]
